### PR TITLE
Fix GHC 7.10 warnings

### PR DESCRIPTION
**Pull request by 23Skidoo**

### CODE REVIEW

**Comment by hvr** [comment]
I'm afraid your patch is obsolete by #141 which avoids CPP and doesn't break on GHC 7.2

**Comment by 23Skidoo** [comment]
Fine with me. Can you please cherry-pick the first commit into your branch?

**Comment by 23Skidoo** [comment]
Closing in favour of #141.

**Comment by hvr** [comment]
> Can you please cherry-pick the first commit into your branch?

done (I hope)

**Pull request closed without merging**
